// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectProbe(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ConnectProbe'](arg1, arg2, arg3, arg4, arg5);
}

export function GetLanguageSettings() {
  return window['go']['main']['App']['GetLanguageSettings']();
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}
