// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConnectProbe(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.ProbeResult>;

export function GetLanguageSettings():Promise<main.LanguageSettings>;

export function SetLanguage(arg1:string):Promise<main.LanguageSettings>;
